config/routes.rb
Nhsrainbow::Application.routes.draw do
  resources :tips

  root :to => "home#index"
  get 'home/index'
  get 'home/autocomplete_tag_name'

  resources :places do
    collection do
      get 'search'
    end
  end

  resources :tags do
    get :autocomplete_tag_name, :on => :collection
  end

end

app/models/tip.rb
class Tip < ActiveRecord::Base
  attr_accessible :place_id, :tip
  belongs_to :place
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tips }
    end
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
    @tip = Tip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tip }
    end
  end

  # GET /tips/new
  # GET /tips/new.json
  def new
    @tip = Tip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tip }
    end
  end

  # GET /tips/1/edit
  def edit
    @tip = Tip.find(params[:id])
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(params[:tip])

    respond_to do |format|
      if @tip.save
        @place = Place.find_by_id(@tip.place_id)
        format.html { redirect_to @place, notice: 'Tip was successfully created.' }
        format.json { render json: @tip, status: :created, location: @tip }
      else
        format.html { render action: "new" }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tips/1
  # PUT /tips/1.json
  def update
    @tip = Tip.find(params[:id])

    respond_to do |format|
      if @tip.update_attributes(params[:tip])
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip = Tip.find(params[:id])
    @tip.destroy

    respond_to do |format|
      format.html { redirect_to tips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/tips/_form.html.erb
<%= form_for(@tip) do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

      <ul>
      <% @tip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place_id %><br />
    <%= f.number_field :place_id %>
  </div>
  <div class="field">
    <%= f.label :tip %><br />
    <%= f.text_area :tip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tips/edit.html.erb
<h1>Editing tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @tip %> |
<%= link_to 'Back', tips_path %>

app/views/tips/index.html.erb
<h1>Listing tips</h1>

<table>
  <tr>
    <th>Place</th>
    <th>Tip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tips.each do |tip| %>
  <tr>
    <td><%= tip.place_id %></td>
    <td><%= tip.tip %></td>
    <td><%= link_to 'Show', tip %></td>
    <td><%= link_to 'Edit', edit_tip_path(tip) %></td>
    <td><%= link_to 'Destroy', tip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tip', new_tip_path %>

app/views/tips/new.html.erb
<h1>New tip</h1>

<%= render 'form' %>

<%= link_to 'Back', tips_path %>

app/views/tips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Place:</b>
  <%= @tip.place_id %>
</p>

<p>
  <b>Tip:</b>
  <%= @tip.tip %>
</p>


<%= link_to 'Edit', edit_tip_path(@tip) %> |
<%= link_to 'Back', tips_path %>