config/routes.rb
Nhsrainbow::Application.routes.draw do
  resources :tips

  root :to => "home#index"
  get 'home/index'
  get 'home/autocomplete_tag_name'

  resources :places do
    collection do
      get 'search'
    end
  end

  resources :tags do
    get :autocomplete_tag_name, :on => :collection
  end

end

app/models/place.rb
require 'open-uri'

class Place < ActiveRecord::Base
  attr_accessible :description, :latitude, :longitude, :name, :place_type, :foursquare_id, :nhs_id
  has_many :tips
  has_many :tags

  @client_id     = 'MIWYYAX3URRPFV3OJTT041F5QIIE1E5GRDNAQ0CLFACR5GHS'
  @client_secret = 'SPQB2PD13XMQVTWT0KFJGORE2OBBOARCCPR5RI0DT0JTSVBI'

  def self.get_from_foursquare_id(id)
    client = Foursquare2::Client.new(:client_id => @client_id, :client_secret => @client_secret)
    venue = client.venue(id)
    place = Place.find_by_foursquare_id(venue.id)
  end

  def self.find_from_coordinates(lat = nil, long = nil)
    locations = Place::find_foursquare_places(lat, long)
    nhs_locations = Place::find_nhs_venues(lat, long)
    locations + nhs_locations
  end

  def self.valid_category?(category)
    return false if category.nil?
    @valid_categories.include?(category.name)
  end

  @valid_categories = [
    "Medical Center",
    "Dentist's Office",
    "Doctor's Office",
    "Emergency Room",
    "Hospital",
    "Laboratory",
    "Optical Shop"
  ]

  def self.find_foursquare_places(lat = nil, long = nil)

    client = Foursquare2::Client.new(:client_id => @client_id, :client_secret => @client_secret)

    locations = []

    @venues = client.search_venues(ll: "#{lat}, #{long}", radius: 10000000)
    @venues.groups[0].items.each do |venue|

      geo = "#{venue.location.lat},#{venue.location.lng}"
      if valid_category?(venue.categories.first)
        place = Place.find_or_create_by_name_and_foursquare_id(
      				:name => venue.name,
      				:foursquare_id => venue.id)
        place.place_type = venue.categories.first.name
        place.latitude = venue.location.lat
        place.longitude = venue.location.lng
        place.save
        locations << place
      end
    end
    locations
  end

  def self.find_postcode(lat = nil, long = nil)
  	postcode_json = open("http://uk-postcodes.com/latlng/#{lat},#{long}.json")
  	parsed_json = ActiveSupport::JSON.decode(postcode_json)
  	parsed_json["postcode"]
  end

  def self.find_nhs_venues(lat = nil, long = nil)
  	postcode = Place::find_postcode(lat, long).gsub!(/\s+/, "")
  	venues = []
    service_types = NhsType.all
    hydra = Typhoeus::Hydra.new
    hydra.cache_getter do |request|
      Rails.cache.read(request.cache_key) rescue nil
    end
    #Set behavior of Hydra Cache Setter
    hydra.cache_setter do |request|
      Rails.cache.write(request.cache_key,request.response,expires_in: request.cache_timeout)
    end
    requests = Array.new
    places_requests = Array.new
    service_types.each do |service_type|
      requests.push(Typhoeus::Request.new("http://v1.syndication.nhschoices.nhs.uk/services/types/#{service_type.uri_key}/postcode/#{postcode}.xml?apikey=NOTKAXDM&range=1", cache_timeout: 1.day))
    end
    requests.map { |request| hydra.queue(request) }
    hydra.run
    hydra2 = Typhoeus::Hydra.new
    hydra2.cache_getter do |request|
      Rails.cache.read(request.cache_key) rescue nil
    end
    #Set behavior of Hydra Cache Setter
    hydra2.cache_setter do |request|
      Rails.cache.write(request.cache_key,request.response,expires_in: request.cache_timeout)
    end
    requests.each do |request|
      doc = Nokogiri::XML(request.response.body)
      doc.css('entry').each do |entry|
        places_requests.push(Typhoeus::Request.new("#{entry.css('id').text}.xml?apikey=NOTKAXDM", cache_timeout: 1.day))
      end
    end
    places_requests.map { |request| hydra2.queue(request) }
    hydra2.run
    places_requests.each do |request|
        doc = Nokogiri::XML(request.response.body).remove_namespaces!
        doc.css('feed').each do |entry|
          place_lat = entry.css('latitude').text.to_f
          place_lng = entry.css('longitude').text.to_f
          name = entry.css('deliverer').text
          if name.empty?
            remove_intro = entry.css('title').text[14..-1]
            name = remove_intro[0..remove_intro.size/2-1]
          end
          place = Place.place_with_name_within_radius(name, 1000, place_lat, place_lng)
          if !place
            place = Place.find_or_create_by_name_and_nhs_id(
             :name => name,
             :nhs_id => URI.parse(entry.css('id').text).path.split("/").last)
            place.latitude = place_lat
            place.longitude = place_lng
            place.save
          end
          venues << place
        end
    end
    venues
  end

  def self.distance place1, latitude, longitude
  a = [place1.latitude, place1.longitude]
  b = [latitude, longitude]
  rad_per_deg = Math::PI/180  # PI / 180
  rkm = 6371                  # Earth radius in kilometers
  rm = rkm * 1000             # Radius in meters

  dlon_rad = (b[1]-a[1]) * rad_per_deg  # Delta, converted to rad
  dlat_rad = (b[0]-a[0]) * rad_per_deg

  lat1_rad, lon1_rad = a.map! {|i| i * rad_per_deg }
  lat2_rad, lon2_rad = b.map! {|i| i * rad_per_deg }

  a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
  c = 2 * Math.asin(Math.sqrt(a))

  rm * c # Delta in meters
  end

  def self.place_with_name_within_radius(name, radius, latitude, longitude)
    places = Place.where(name: name)
    places.each do |place|
      return place if Place.distance(place, latitude, longitude) < radius
    end
    nil
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # GET /places
  # GET /places.json
  def index

    if params[:lat] && params[:long]
      @places = Place::find_from_coordinates(params[:lat], params[:long])
      #TODO sort by distance to here
    else
      @places = Place.all
    end
    @places.uniq!
    @places = @places.sort_by { |p| Place.distance(p, params[:lat].to_f, params[:long].to_f) }
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place::find_by_id(params[:id])
    @tip = Tip.new(place_id: @place.id)
    @tag = Tag.new(place_id: @place.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  #GET /places/search?terms=taggy,taggy2
  def search
     terms_array = params[:terms].split(",")
     tags = []
     terms_array.each do |term|
       tags << term.
     end
     @places = Place.all
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :place_type %><br />
    <%= f.text_field :place_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/_tag.html.erb
<h4>Tag this information</h4>

<%= form_for(@tag, remote: true) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :place_id %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit(class: 'btn btn-success') %>
  </div>
<% end %>

app/views/places/_tip.html.erb
<h4>Add information about this practice</h4>

<%= form_for(@tip) do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

      <ul>
      <% @tip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :tip %>
  </div>

  <%= f.hidden_field :place_id %>

  <div class="actions">
    <%= f.submit(class: 'btn btn-success', value: 'Save') %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Description</th>
    <th>Place type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @places.each do |place| %>
  <tr>
    <td><%= place.name %></td>
    <td><%= place.latitude %></td>
    <td><%= place.longitude %></td>
    <td><%= place.description %></td>
    <td><%= place.place_type %></td>
    <td><%= link_to 'Show', place %></td>
    <td><%= link_to 'Edit', edit_place_path(place) %></td>
    <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<h3><%= @place.name %></h3>

<div class="panel panel-default">
  <div class="panel-body">
    <em>Information about this place</em>
    <ul class="list-group">
      <% @place.tips.each do |tip| %>
        <li class="list-group-item"><%= tip.tip%></li>
      <% end %>
    </ul>

    <div id="tags">
      <% @place.tags.each do |tag| %>
        <span class="label label-warning"><%= tag.name %></span>&nbsp;
      <% end %>
    </div>

  </div>
  <div class="panel-footer">
    <p>Tag this data</p>
    <%= render 'tag' %>
    <%= render 'tip' %>

  </div>
</div>

<%= link_to 'Back', root_path, { class: 'btn btn-danger' } %>